### ISSUE TITLE
postNotification should be a method on Notification

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#19]
Global functions always feel wrong, especially with Apple doing away with them from things like map/filter/etc...

If you're going to postNotification, you have to pass it a Notification object.  Why isn't postNotification a method in the Notification struct?

**Comment by jessesquires** [comment]
hey @grosch — another good point :smile: 

>Global functions always feel wrong

I think this depends on your background. Those familiar with FP should find this familiar.

>especially with Apple doing away with them from things like map/filter/etc...

Very good point. This library was written before protocol extensions in Swift.

--------------------------------------

My initial reaction to this was that `Notification` should be a dumb container, and a `post()` function would make it too smart. And, top-level functions are "more functional" (a design goal of this library). 

However, given protocol extensions, I think this makes sense. "Create a notification and post it."

Because `postNotification()` uses dependency injection, this doesn't really add dependencies to the struct.

I'm assuming you're proposing adding the following to `Notification`?

````swift
public func post(value: Value, center: NSNotificationCenter = .defaultCenter()) {
    // ...
}

// Usage

let notif = Notification(...)
notif.post(myValue)
````

If so, sounds good! :+1: Thanks for the suggestion!

**Comment by jessesquires** [comment]
Another benefit of this is that the `post()` function no longer needs to have generic type parameters. Much cleaner.

**Comment by grosch** [comment]
Yes, exactly.  Thanks for being open to the idea!

**Comment by jessesquires** [comment]
If you want to submit a PR, let me know. :smile: 

Otherwise, I'll tackle this and get `v3.0` of the library out by next week. :+1:

**Comment by grosch** [comment]
PR submitted.
